Add controllers
AlexandraKozhevnikova/java-shareit pull request #1
Opened 2023-01-17 14:44 UTC by AlexandraKozhevnikova

Добавлены методы из ТЗ 13 спринта

2023-01-17 15:31 UTC, AlexandraKozhevnikova commented
Я немного накосячила с дз. Первые четыре коммита оказались в ветке   main  и в ПР попали только 4 комита из ветки     add-controller. Пока не знаяю как безопасто все коммиты перенести в фичеветку, такой гит мы еще не проходили. Надеюсь можно сдать так, так как функционал и тесты ок

2023-01-18 06:28 UTC, Frilock requested changes
Добрый день, оставил ряд комментариев к работе

2023-01-18 06:28 UTC, Frilock commented on src/main/java/ru/practicum/shareit/exception/ApiError.java
> +    String type;
А почему поля не приватные?

2023-01-18 06:28 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                              @Valid @RequestBody ItemDto itemDto) {
Вижу аннотацию Valid, а без аннотации Validated над классом у Вас будет работать валидация? Вы тестировали?

2023-01-18 06:28 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        Item item = itemMapper.dtoToItem(itemDto);
Вообще конечно допустимый вариант преобразования дто в ентити в контролере, но лично я бы Вам предложил перенести эту логику в сервис. А в контролере оставить только вызов метода сервиса

2023-01-18 06:28 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    @GetMapping()
Пустые скобки не нужны

2023-01-18 06:28 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemInMemoryRepository.java
> +                .filter(it -> it.getDescription().toLowerCase().contains(text.toLowerCase())
Тут можно использовать StringUtils.containsIgnoreCase - будет компактнее, а на строчке выше BooleanUtils.isTrue(..)

2023-01-18 06:28 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        if (text.equals("")) {
Данную конструкцию можно заменить на тернарное выражение, будет выглядеть компактнее.

2023-01-18 06:28 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/UserInMemoryRepository.java
> +    @Autowired
Зачем тут пустой конструктор? Кроме того, если конструктор один, то можно Autowired не писать

2023-01-18 06:28 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/UserInMemoryRepository.java
> +    private HashSet<String> emails = new HashSet<>();
В сигнатуре методов сначала лучше указывать интерфейс, а при инициализации - реализацию

2023-01-18 06:28 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/UserInMemoryRepository.java
> +        } else {
Смотрите, вообще тут идет лишняя вложенность. Вы можете сначала проверить emails.contains(user.getEmail()) - кинуть исключение в блоке if, а затем дальше продолжать писать код уже без блока else
int id = getNexId();
            user.setId(id);
            users.put(user.getId(), user);
            emails.add(user.getEmail());
            return users.get(id);

2023-01-18 06:28 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    Integer id;
Модификаторы

2023-01-18 14:12 UTC, AlexandraKozhevnikova commented on src/main/java/ru/practicum/shareit/exception/ApiError.java
> +    String type;
забыла

2023-01-18 14:18 UTC, AlexandraKozhevnikova commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                              @Valid @RequestBody ItemDto itemDto) {
1) Решение тестируется коллекцией постман, которая прикручена к  Checks на гитхаб у этого репозитория

из логов джобы (скриншотом не получается приложить):

```
Tue, 17 Jan 2023 17:03:03 GMT
↳ Item create without available
Tue, 17 Jan 2023 17:03:03 GMT
  POST http://localhost:8080/items  
Tue, 17 Jan 2023 17:03:03 GMT
  400 Bad Request ★ 8ms time ★ 408B↑ 254B↓ size ★ 10↑ 4↓ headers ★ 0 cookies
Tue, 17 Jan 2023 17:03:03 GMT
  ┌ ↑ raw ★ 102B
Tue, 17 Jan 2023 17:03:03 GMT
  │ {
Tue, 17 Jan 2023 17:03:03 GMT
  │     "name": "Отвертка",
Tue, 17 Jan 2023 17:03:03 GMT
  │     "description": "Аккумуляторная отвертка"
Tue, 17 Jan 2023 17:03:03 GMT
  │ }
Tue, 17 Jan 2023 17:03:03 GMT
  └ 
Tue, 17 Jan 2023 17:03:03 GMT
  ┌ ↓ application/json ★ text ★ json ★ utf8 ★ 110B
Tue, 17 Jan 2023 17:03:03 GMT
  │ [{"message":"'available' must not be blank","error":{"
Tue, 17 Jan 2023 17:03:03 GMT
  │ type":"validation","description":"value is not valid"}
Tue, 17 Jan 2023 17:03:03 GMT
  │ }]
Tue, 17 Jan 2023 17:03:03 GMT
  └
Tue, 17 Jan 2023 17:03:03 GMT
  prepare   wait    dns-lookup   tcp-handshake   transfer-start   download   process   total 
Tue, 17 Jan 2023 17:03:03 GMT
  1ms       339µs   (cache)      (cache)         5ms              1ms        55µs      9ms   
Tue, 17 Jan 2023 17:03:03 GMT

Tue, 17 Jan 2023 17:03:03 GMT
  ✓  Status code is 400
Tue, 17 Jan 2023 17:03:03 GMT

Tue, 17 Jan 2023 17:03:03 GMT
↳ Item create with empty name
Tue, 17 Jan 2023 17:03:03 GMT
  POST http://localhost:8080/items  
Tue, 17 Jan 2023 17:03:03 GMT
  400 Bad Request ★ 7ms time ★ 415B↑ 249B↓ size ★ 10↑ 4↓ headers ★ 0 cookies
Tue, 17 Jan 2023 17:03:03 GMT
  ┌ ↑ raw ★ 109B
Tue, 17 Jan 2023 17:03:03 GMT
  │ {
Tue, 17 Jan 2023 17:03:03 GMT
  │     "name": "",
Tue, 17 Jan 2023 17:03:03 GMT
  │     "description": "Аккумуляторная отвертка",
Tue, 17 Jan 2023 17:03:03 GMT
  │     "available": true
Tue, 17 Jan 2023 17:03:03 GMT
  │ }
Tue, 17 Jan 2023 17:03:03 GMT
  └ 
Tue, 17 Jan 2023 17:03:03 GMT
  ┌ ↓ application/json ★ text ★ json ★ utf8 ★ 105B
Tue, 17 Jan 2023 17:03:03 GMT
  │ [{"message":"'name' must not be blank","error":{"type"
Tue, 17 Jan 2023 17:03:03 GMT
  │ :"validation","description":"value is not valid"}}]
Tue, 17 Jan 2023 17:03:03 GMT
  └
Tue, 17 Jan 2023 17:03:03 GMT
  prepare   wait    dns-lookup   tcp-handshake   transfer-start   download   process   total 
Tue, 17 Jan 2023 17:03:03 GMT
  2ms       655µs   100µs        [310](https://github.com/AlexandraKozhevnikova/java-shareit/actions/runs/3941520970/jobs/6744043317#step:11:311)µs           4ms              1ms        36µs      9ms   
Tue, 17 Jan 2023 17:03:03 GMT

Tue, 17 Jan 2023 17:03:03 GMT
  ✓  Status code is 400
Tue, 17 Jan 2023 17:03:03 GMT

Tue, 17 Jan 2023 17:03:03 GMT
↳ Item create with empty description
Tue, 17 Jan 2023 17:03:03 GMT
  POST http://localhost:8080/items  
Tue, 17 Jan 2023 17:03:03 GMT
  400 Bad Request ★ 7ms time ★ 362B↑ 256B↓ size ★ 10↑ 4↓ headers ★ 0 cookies
Tue, 17 Jan 2023 17:03:03 GMT
  ┌ ↑ raw ★ 57B
Tue, 17 Jan 2023 17:03:03 GMT
  │ {
Tue, 17 Jan 2023 17:03:03 GMT
  │     "name": "Отвертка",
Tue, 17 Jan 2023 17:03:03 GMT
  │     "available": true
Tue, 17 Jan 2023 17:03:03 GMT
  │ }
Tue, 17 Jan 2023 17:03:03 GMT
  └ 
Tue, 17 Jan 2023 17:03:03 GMT
  ┌ ↓ application/json ★ text ★ json ★ utf8 ★ 112B
Tue, 17 Jan 2023 17:03:03 GMT
  │ [{"message":"'description' must not be blank","error":
Tue, 17 Jan 2023 17:03:03 GMT
  │ {"type":"validation","description":"value is not valid
Tue, 17 Jan 2023 17:03:03 GMT
  │ "}}]
Tue, 17 Jan 2023 17:03:03 GMT
  └
Tue, 17 Jan 2023 17:03:03 GMT
  prepare   wait    dns-lookup   tcp-handshake   transfer-start   download   process   total 
Tue, 17 Jan 2023 17:03:03 GMT
  1ms       787µs   91µs         723µs           3ms              1ms        41µs      8ms   
Tue, 17 Jan 2023 17:03:03 GMT

Tue, 17 Jan 2023 17:03:03 GMT
  ✓  Status code is 400

2023-01-18 14:25 UTC, AlexandraKozhevnikova commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                              @Valid @RequestBody ItemDto itemDto) {
Когда разбиралась с валидацией опиралась на эти статьи:
https://www.baeldung.com/spring-valid-vs-validated
https://medium.com/javarevisited/are-you-using-valid-and-validated-annotations-wrong-b4a35ac1bca4

2023-01-18 14:32 UTC, ms-ask commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        Item item = itemMapper.dtoToItem(itemDto);
Уточните пожалуйста почему такой способ предпочтительнее?

Из того что поняла и почему я выбрала такую реализацию:
сейчас у меня есть котроллер и сервис - одна точно входа в приложение.
Потом появится например MQ, который возможно будет иметь свой ItemRequestDTO (так как для другого потребителя и контракт может быть разным), тогда опять же мапинг в энтити будет происходить в классе приема сообщений, а сервису уже передавать чистое энтити.
Итого, сколько бы разных клиентов не подключилось, сервис один и работает только с энтити.
Если в классе сервиса будет мапинг реквестов, то придется под   MQ  либо делать свой сервис, либо перегружать метод сервиса чтобы он мог принимать и  RestItemRequestDTO  и MqItemRequestDto, что является явно слабым местом в масштабированности и низкой связанности

2023-01-18 14:34 UTC, AlexandraKozhevnikova commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    @GetMapping()
убрала

2023-01-18 14:38 UTC, AlexandraKozhevnikova commented on src/main/java/ru/practicum/shareit/item/ItemInMemoryRepository.java
> +                .filter(it -> it.getDescription().toLowerCase().contains(text.toLowerCase())
спасибо) помню что был метод  containsIgnoreCase() но не смогла найти )

2023-01-18 14:48 UTC, AlexandraKozhevnikova commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        if (text.equals("")) {
спасибо, применила

2023-01-18 14:49 UTC, AlexandraKozhevnikova commented on src/main/java/ru/practicum/shareit/user/UserInMemoryRepository.java
> +    @Autowired
Мне просто нравится явно указывать, чтобы видеть место создания бина.
пока тяжело держать в голове, что у любого класса есть пустой конструктор, что спинг находя один конструктор  возьмет его

2023-01-18 14:50 UTC, AlexandraKozhevnikova commented on src/main/java/ru/practicum/shareit/user/UserInMemoryRepository.java
> +    private HashSet<String> emails = new HashSet<>();
исправила на интерфейсы

2023-01-18 18:09 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                              @Valid @RequestBody ItemDto itemDto) {
Да вы правы, Validated для групповой валидации, а эта для валидации на метод

2023-01-18 18:12 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/UserInMemoryRepository.java
> +    @Autowired
Можете пока оставить (хотя вы только для одного бина такое делаете, в других же местах такого у Вас не видел), но в целом на работе попросят убрать такой код

2023-01-18 18:17 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        Item item = itemMapper.dtoToItem(itemDto);
Дискуссионный вопрос. Не очень понял, где будет узкое место в плане масштабируемости, но в целом, не вижу проблемы, если у Вас появится еще 1 реализация интерфейса. Внутри интерфейса делаете свой другой маппер и мапите так как Вам угодно, зато не будет никакой логики в контроллере и никаких ветвлений.
Кроме того, из личного опыта, сейчас работаю на довольно большом проекте и мы довольно часто сталкивались с различного рода ошибками при работе с сущностями хибернейта (в частности ошибками, когда нет сессии (т.е. делаете запрос в БД, а он Вам в ответ, что у Вас нет сессии, конечно, такие проблемы решаемы, но все же довольно муторные), так вот решили проблемы путем отказа от работы с бизнес сущностью в бизнес логике приложения - работаем только с ДТО. А уже в конце когда нам нужно сохранить данные в БД мы из ДТО преобразуем в entity и сохраняем.

2023-01-18 18:19 UTC, Frilock approved these changes
Мне нравится, что вы пытаетесь глубже разобраться в проблемах и задаете вопросы, это хорошее качество. Работу принял

2023-01-18 20:32 UTC, merged