Add bookings (14 sprint)
AlexandraKozhevnikova/java-shareit pull request #2
Opened 2023-01-29 18:01 UTC by AlexandraKozhevnikova

Проект ShareIt. Техническое задание. Часть 2

2023-01-29 18:19 UTC, AlexandraKozhevnikova commented
На чекстайле одна ошибка:

 Execution default-cli of goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.2:checkstyle failed: A required class was missing while executing org.apache.maven.plugins:maven-checkstyle-plugin:3.1.2:checkstyle: org/apache/commons/beanutils/converters/ArrayConverter

Наставнику написала но пока ответа нет
Тесты проходят, проект компилится (нагуглить как править ошибку не удалось)

2023-01-30 06:18 UTC, Frilock requested changes
Доброе утро, я оставил немного комментариев к  работе. Тесты проходят, с задачей в целом справились, лично на мой взгляд, Вы себе задачу усложняете, используете кучу разных библиотек, и у Вас решения получаются довольно не стандартные. Думаю что это не плохо =)

2023-01-30 06:18 UTC, Frilock commented on pom.xml
> +        <dependency>
Для чего эти зависимости логгера? Вроде в parent есть все нужные Вам библиотеки

2023-01-30 06:18 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +    private BookingOrderMapping bookingMapping;
А почему поля не final? Только ведь в конструкторе сетятся

2023-01-30 06:18 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +    @SneakyThrows
Предложил бы работать с исключениями более явно, но дело Ваше конечно

2023-01-30 06:18 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        if (status == BookingStatus.ALL) {
Слишком много else условий, замените на switch case

2023-01-30 06:18 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/DateConsistencyValidator.java
> +        return value.getStart().isBefore(value.getEnd()) && value.getStart().isAfter(LocalDateTime.now());
Мы в данный момент времени уверены что обе даты не могут быть null?

2023-01-30 06:18 UTC, Frilock commented on src/main/java/ru/practicum/shareit/exception/ErrorResponse.java
> +    String error;
Почему модификаторы доступа отстуствуют?

2023-01-30 06:18 UTC, Frilock commented on src/main/java/ru/practicum/shareit/exception/ExceptionApiHandler.java
> +    private static final Logger log = LogManager.getLogger(ExceptionApiHandler.class);
Зачем такую странную библиотеку использовать?) Берите стандартную и используйте от lombok slf4j

2023-01-30 06:18 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        Item item = itemService.getItemWithUserAccess(itemId, userId);
Опять же, довольно много сторонней логики, почему бы все это в сервис не перетащить?

2023-01-30 06:18 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +                .findAll(isAvailable
в 1 строчку влезает

2023-01-30 06:18 UTC, Frilock commented on src/main/resources/schema.sql
> +    email     VARCHAR UNIQUE NOT NULL,
Смотрите, общий комментарий по скрипту и модели данных. Вы когда архитектуру БД планируете, нужно продумать размерность полей, то есть, например, поле код не должно иметь стандартный размер в 255, а его можно сделать, например, в 50 символов, а вот для описание нужно больше места, поэтому логичнее под данную колонку выделить, например, 1000. 
Кроме того, после того как Вы все указали в скрипте, тоже самое нужно сделать в аннотации Column для классов моделей. Указать размерность поля, а также дополнительные флаги, например, nullable = false.

2023-01-30 08:33 UTC, AlexandraKozhevnikova commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        if (status == BookingStatus.ALL) {
Очень хотела действовать через  switch, но столкнулась с тем  что выражение case  не может быть получение значение из енама 
Скриншоты картинкой прикреплять не могу, ссылка https://disk.yandex.ru/i/1TQOQI1U6u94ug

2023-01-30 08:34 UTC, AlexandraKozhevnikova commented on pom.xml
> +        <dependency>
Все что связано с логером - тут ответ один: не получилось стандартным образом
и начала гуглить как увиделть логи

Мне нужны были логи в консоли когда выбрасывается перехватывающее исключение (и никак не получалось) поэтому столько пришось "навертеть"

2023-01-30 08:38 UTC, AlexandraKozhevnikova commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +    private BookingOrderMapping bookingMapping;
наверно не до конца понимаю когда они нужны а когда нет, поэтому не ставлю.
Спасибо, поправлю на final

2023-01-30 08:39 UTC, AlexandraKozhevnikova commented on src/main/java/ru/practicum/shareit/exception/ErrorResponse.java
> +    String error;
добавлю

2023-01-30 08:39 UTC, AlexandraKozhevnikova commented on src/main/java/ru/practicum/shareit/exception/ExceptionApiHandler.java
> +    private static final Logger log = LogManager.getLogger(ExceptionApiHandler.class);
все то же, не получилось сделать стандартно как в прошлом проекте(

2023-01-30 08:40 UTC, AlexandraKozhevnikova commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        Item item = itemService.getItemWithUserAccess(itemId, userId);
на примере сложного дто стало очевидно что мапперам место в сервисе))) Но из экономии времени не стала переписывать

2023-01-30 08:41 UTC, AlexandraKozhevnikova commented on src/main/resources/schema.sql
> +    email     VARCHAR UNIQUE NOT NULL,
спасибо, сделаю

2023-01-30 11:47 UTC, AlexandraKozhevnikova commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        if (status == BookingStatus.ALL) {
а как обойти не поняла, поэтому передалала на иф-елсе. может даже на 11 джаве и не получится со свичом

2023-01-30 11:48 UTC, AlexandraKozhevnikova commented on src/main/java/ru/practicum/shareit/booking/DateConsistencyValidator.java
> +        return value.getStart().isBefore(value.getEnd()) && value.getStart().isAfter(LocalDateTime.now());
Так как сейчас данные приходят только с хттп - запроса, то там стоит  @NotNull  на оба поля

2023-01-31 06:27 UTC, Frilock requested changes
Доброе утро, еще пара комментариев

2023-01-31 06:27 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        if (booking.getItem().getIsAvailable() == false) {
Можно упростить  if (!booking.getItem().getIsAvailable())

2023-01-31 06:27 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +                .map(it -> bookingMapping.entityToDto(it))
Можно упростить на                 .map(bookingMapping::entityToDto)

2023-01-31 06:27 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        if (status == BookingStatus.ALL) {
switch (status) {
            case ALL:
                System.out.println();
            case PAST:
                System.out.println();
        }
       должно работать

2023-01-31 06:27 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/model/BookingOrder.java
> +    @PostLoad
А зачем Вам это?
    @PostLoad
    void fillTransient() {
        if (bookingStatusDbCode > 0) {
            this.status = BookingStatus.ofDbCode(bookingStatusDbCode);
        }
    }

    @PrePersist
    @PreUpdate
    void fillPersistent() {
        if (status != null) {
            this.bookingStatusDbCode = status.getDbCode();
        }
    }
    
    Кроме того, почему методы без модификатора?

2023-01-31 06:27 UTC, Frilock commented on src/main/java/ru/practicum/shareit/exception/ExceptionApiHandler.java
> +    private static final Logger log = LogManager.getLogger(ExceptionApiHandler.class);
а что конкретно не получилось? Нет логов в консоль? Или что? Вам бы у коллег проконсультироваться, а то это же по сути просто другая реализация логгера (которую никогда не видел я).

2023-01-31 06:27 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemInMemoryRepository.java
> +//package ru.practicum.shareit.item;
Удаляйте класс если не используется он

2023-01-31 06:27 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +                       @Lazy
Играетесь с аннотациями? или какой то конкретный кейс Вам нужен? По идее можете как в других местах заменить конструктор на AllArgs.. или RequiredArgs...

2023-01-31 06:27 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        BooleanExpression isAvailable = QItem.item.isAvailable.isTrue();
А вообще зачем Вам библиотека querydsl? Тут тоже усложняете

2023-01-31 13:51 UTC, ms-ask commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        if (booking.getItem().getIsAvailable() == false) {
для читаемости написала в длинном варианте

2023-02-02 18:11 UTC, AlexandraKozhevnikova commented on src/main/java/ru/practicum/shareit/exception/ExceptionApiHandler.java
> +    private static final Logger log = LogManager.getLogger(ExceptionApiHandler.class);
[AlexandraKozhevnikova](https://github.com/AlexandraKozhevnikova) [3 days ago](https://github.com/AlexandraKozhevnikova/java-shareit/pull/2#discussion_r1090307764)
Все что связано с логером - тут ответ один: не получилось стандартным образом
и начала гуглить как увиделть логи

Мне нужны были логи в консоли когда выбрасывается перехватывающее исключение (и никак не получалось) поэтому столько пришось "навертеть"

2023-02-02 18:14 UTC, ms-ask commented on src/main/java/ru/practicum/shareit/booking/model/BookingOrder.java
> +    @PostLoad
https://www.baeldung.com/jpa-persisting-enums-in-jpa
 п. 3

2023-02-02 18:14 UTC, AlexandraKozhevnikova commented on src/main/java/ru/practicum/shareit/booking/model/BookingOrder.java
> +    @PostLoad
вроде дефолтный пакетный тут как раз подходит

2023-02-02 18:18 UTC, AlexandraKozhevnikova commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +                       @Lazy
https://translated.turbopages.org/proxy_u/en-ru.ru.f0c3c572-63dbfe39-eb10b261-74722d776562/https/www.baeldung.com/circular-dependencies-in-spring

п 4.2

2023-02-02 18:22 UTC, AlexandraKozhevnikova commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        BooleanExpression isAvailable = QItem.item.isAvailable.isTrue();
https://practicum.yandex.ru/learn/java-developer/courses/ec5e03ed-e12f-43c5-93d1-638a79454e03/sprints/88793/topics/2164e09b-f7a0-4c05-b4e2-e8f232974790/lessons/a2b82550-5872-46dc-a5fe-5af4d46940ea/

два последний абзаца

2023-02-02 20:20 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +                       @Lazy
Если появляются циклические зависимости это значит что архитектура приложения не верная, или архитектура БД. Давайте на данном этапе оставим так

2023-02-02 20:25 UTC, Frilock approved these changes
Добрый вечер, работу принимаю, отдельный лайк за оригинальное решение, однако все же на мой взгляд усложняете сильно. По поводу циклических ссылок - если они появляются это признак плохой архитектуры БД или приложения, и всякие костыли для их решения, на мой взгляд, не очень хорошая идея. Но в общем на данном этапе окей.

2023-02-02 21:02 UTC, AlexandraKozhevnikova commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +                       @Lazy
согласна по архитектуре, но на сколько я поняла фаил Советы ментора, то требовалось реализовать в ItemService, хотя сервис  Booking мог бы это делать (все данные по контексту есть)  и тогда без циклической зависимости кажется бы обошлось




```
Это единственный эндпоинт для работы с отзывами — разместите его в
ItemController . Создавать отдельный контроллер не потребуется: это было бы
уместно в приложении с более продвинутым функционалом отзывов. А вот
написать DTO-класс для комментария нужно.
Добавьте в нужные DTO-объекты список отзывов. Для получения списка из БД
реализуйте обращение к новому репозиторию CommentRepository в соответствующих
методах в ItemServiceImpl . Вероятно, вам также захочется добавить в
CommentRepository новые методы для поиска комментариев к вещи.
Убедитесь, что отзывы успешно добавляются и отображаются

2023-02-02 21:02 UTC, merged