Add item requests (15 sprint)
AlexandraKozhevnikova/java-shareit pull request #3
Opened 2023-01-30 16:13 UTC by AlexandraKozhevnikova

Проект ShareIt. Техническое задание. Часть 3

2023-02-07 20:56 UTC, AlexandraKozhevnikova commented
Добрый день!
Тесты в постмане все проходят,
судя по идеи юнит тесты с высоким покрытием, возможно автогенеренные классы занижают процент
Не могу добить одну десятую процента( в чате у наставника и ребят спросила - решения пока нет)
https://disk.yandex.ru/i/2Z1yYeYAcwVM9w

2023-02-08 16:19 UTC, Frilock requested changes
Добрый вечер, все в целом хорошо, каких то серьезных вопросов у меня к Вам нет. Написал несколько небольших комментариев, которые лучше поправить. Если у Вас будут какие то вопросы или что то Вас смущает, вы можете мне написать в пачку.

2023-02-08 16:19 UTC, Frilock commented on pom.xml
> +            <version>1.9.4</version>
Вроде обсуждали с вами уже, просьба поправить

Версии библиотек, которые вы подключаете в pom файле, принято указывать в properties, по аналогии с версией Java, а в поле version самой библиотеки указывать так ${example-lib.version}. Это нужно для того, чтобы версии библиотек находились в одном месте и их изменении проходило безболезненно.

2023-02-08 16:19 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +                        QPageRequest.of(from.orElse(0), size.orElse(100))
Если в код не погружаться, то будет не ясно, что значат числа 0 и 100, в коде лучше отказаться от использования "магических" чисел. Перенесите их в константы, где по имени сразу станет понятно для чего те или иные данные

2023-02-08 16:19 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    @Transactional()
Пустые скобки не нужны

2023-02-08 16:19 UTC, Frilock commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
> +    @Column(name = "id")
В данном случае аннотация Column не нужна, поскольку Ваше поле в БД называется также как и тут

2023-02-08 16:19 UTC, Frilock commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +        userService.getUserById(userId);
Мы вроде с Вами обсуждали (возможно не с вами), тот момент, что лучше не проверять наличие данных в БД путем поиска по идентификатору. Это не явное поведение, оно будет путать. 
Кроме того, эту проверку лучше перенести в метод сервиса и там ее вызывать. Как вариант, оберните этот поиск в другой метод, например, checkUserExist с возвращаемым значением тру или фолс, и если фолс то бросайте свое исключение.

2023-02-08 16:19 UTC, Frilock commented on src/main/java/ru/practicum/shareit/request/ItemRequestService.java
> +                .filter(it -> !it.isBlank())
Предлагаю заменить на StringUtils

2023-02-08 16:19 UTC, Frilock commented on src/main/resources/schema.sql
> +    description TEXT      NOT NULL,
Стандартный размер разве подходит для этого поля? Предлагаю явно указать значение, например, в 1000

2023-02-08 16:19 UTC, Frilock commented on src/test/java/ru/practicum/shareit/controllerEndpointTest/ItemControllerTest.java
> +
Слишком много пропусков пустых, так не принято

2023-02-08 16:19 UTC, Frilock commented on src/test/java/ru/practicum/shareit/controllerMethodTest/BookingOrderControllerUnitTest.java
> +        assertThrows(AccessDeniedException.class, () -> bookingOrderController.getBookingOrder(anyLong(), anyLong()));
В негативных кейсах еще как вариант можно проверять само сообщение, то есть вы делаете так - 
AccessDeniedException exception = assertThrows ....
assertTrue(exception.contains....)

Чтобы уж точно быть уверенным в том, что вы нужное исключение поймали

2023-02-08 16:19 UTC, Frilock commented on src/test/java/ru/practicum/shareit/controllerMethodTest/ItemRequestControllerUnitTest.java
> +        verify(userService, times(1))
Вроде в 1 строчку все влезает, не вижу смысла лишние переносы делать (Но это на Ваше усмотрение)

2023-02-08 20:39 UTC, AlexandraKozhevnikova commented on pom.xml
> +            <version>1.9.4</version>
перенесла в проперти

2023-02-08 20:45 UTC, AlexandraKozhevnikova commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +                        QPageRequest.of(from.orElse(0), size.orElse(100))
согласна, вынесла в константы

2023-02-08 20:47 UTC, AlexandraKozhevnikova commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
> +    @Column(name = "id")
да, я понимаю, наставник рекомендовал везде ставить, чтобы читалось однообразно

2023-02-08 20:52 UTC, AlexandraKozhevnikova commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +        userService.getUserById(userId);
про наименование согласна, путает - переделала

выкидывать самой тут эксепшен -не стала, тк эксепшен одинаковый, вполне подходит тот что в методе (чтобы dry)

убирать в сервис_ об этом думала, но плюс это что меньше логике в контроллере, минус: это что метод перестанет быть "единичной ответсвенности" (если я правильно понимаю этот принцип)
воторой минус, когда у меня начали возникать цикличные зависимости в сервисах, тк они ходят друг в друга проверять есть ли сущности. А проверка на стороне контроллера получается не сможет привести к цикличной зависимости

2023-02-08 20:53 UTC, AlexandraKozhevnikova commented on src/main/java/ru/practicum/shareit/request/ItemRequestService.java
> +                .filter(it -> !it.isBlank())
согласна, так посимпотичнее

2023-02-08 20:56 UTC, AlexandraKozhevnikova commented on src/main/resources/schema.sql
> +    description TEXT      NOT NULL,
для TEXT кажется нельзя указать ограничение

2023-02-08 20:56 UTC, AlexandraKozhevnikova commented on src/test/java/ru/practicum/shareit/controllerEndpointTest/ItemControllerTest.java
> +
поправила

2023-02-08 20:58 UTC, AlexandraKozhevnikova commented on src/test/java/ru/practicum/shareit/controllerMethodTest/BookingOrderControllerUnitTest.java
> +        assertThrows(AccessDeniedException.class, () -> bookingOrderController.getBookingOrder(anyLong(), anyLong()));
да, помню это из тренажера, но сил никаких нет на качество тестов, учитывая какое количество в этом спринте пришлось сделать за раз ради этих метрик (итак уже все дедлайны сгорели((( )

2023-02-08 20:58 UTC, AlexandraKozhevnikova commented on src/test/java/ru/practicum/shareit/controllerMethodTest/ItemRequestControllerUnitTest.java
> +        verify(userService, times(1))
да, влезет
так выглядет читабельнее имхо, вроде даже так показывали на хардах или в мануале где-то

2023-02-08 21:46 UTC, AlexandraKozhevnikova commented
В чате когорты идет переписка что тест неверный
Test get all bookings | AssertionError: bookings count in total: expected +0 to deeply equal 1

[Bookings get all with from = 2 & size = 2 when all=3] - так как тут идекс должен стоять 1 (вторая страница)
не хочется писать костыль под один тест

2023-02-09 05:55 UTC, Frilock commented on src/main/resources/schema.sql
> +    description TEXT      NOT NULL,
Да, что то не обратил внимание, думал там varchar

2023-02-09 05:59 UTC, Frilock approved these changes
Доброе утро, работу принимаю, но у Вас слетел 1 тест, хотя в прошлой сборке он проходил, просьба поправить его тоже.

2023-02-09 14:49 UTC, merged